# Generated by Django 3.1.1 on 2021-05-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datchiki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pribori',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemChanges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_oper', models.DateTimeField(null=True)),
                ('quantity_datchik', models.FloatField(null=True)),
                ('quantity_pribor', models.FloatField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('datchik_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sma2.datchiki')),
                ('pribor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sma2.pribori')),
            ],
        ),
        migrations.CreateModel(
            name='Rezim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('len_rezim', models.FloatField(null=True)),
                ('normativ_datchik', models.FloatField(null=True)),
                ('normativ_pribor', models.FloatField(null=True)),
                ('datchik_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sma2.datchiki')),
                ('pribor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sma2.pribori')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('time_oper', models.DateTimeField(null=True)),
                ('value', models.FloatField(null=True)),
                ('ediz', models.TextField(null=True)),
                ('prim', models.TextField(null=True)),
                ('rezim_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sma2.rezim')),
            ],
        ),
        migrations.AddField(
            model_name='pribori',
            name='zone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sma2.zone'),
        ),
        migrations.AddField(
            model_name='datchiki',
            name='zone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sma2.zone'),
        ),
    ]
